%% Test script with arbitrary values to check the modal synthesis functions

project_path = genpath('../');
addpath(project_path);

string_modes_number = 20;
body_modes_number = 30;
modes_number = body_modes_number + string_modes_number;

[~, ~, string_params] = F_string_model( string_modes_number );

%% Efective stiffnesses/masses and Q-factors computation (via measures?)

% Temporary arbitrary values
effective_stiffnesses_v = ones(body_modes_number,1);

effective_masses_v = ones(body_modes_number,1);
body_q_factors_v = ones(body_modes_number,1) * 10^9;
string_q_factors_v = ones(string_modes_number,1) * 10^9;

%% System matrices computation
[ mass_m ] = F_compute_mass_m( ...
    string_modes_number, body_modes_number, ...
    string_params.string_length, string_params.string_linear_mass, ...
    effective_masses_v );

[ stiffness_m ] = F_compute_stiffness_m( ...
    string_modes_number, body_modes_number, ...
    string_params.string_bending_stiffness, ...
    string_params.string_length, string_params.string_tension, ...
    effective_stiffnesses_v );

[ dissipation_m ] = F_compute_dissipation_m( ...
    string_modes_number, ...
    string_params.string_linear_mass, string_params.string_tension, ...
    effective_stiffnesses_v, effective_masses_v, ...
    body_q_factors_v, string_q_factors_v );

%% Modes computation
[ modes_m, complex_natural_frequencies_v ] = ...
    F_compute_modes_m( dissipation_m, mass_m, stiffness_m );

%% Resynthesis

duration_s = 10;
Fs_Hz = 44100;

[ modal_synthesis_v ] = F_modal_synth( ...
    string_params.x_listening, ...
    string_modes_number, body_modes_number, ...
    string_params.string_length, ...
    modes_m, complex_natural_frequencies_v, ...
    mass_m, ...
    duration_s, Fs_Hz );